# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('testo', models.TextField()),
                ('voto', models.PositiveIntegerField(verbose_name=5)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestito.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestito.UserProfile')),
            ],
        ),
    ]
