# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestito', '0004_auto_20190120_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
